### PR TITLE
Setup project files

### LINKED ISSUE #13: Lint Code

### PR DESCRIPTION
**Pull request by Karyum**
related to #11
close #13

### CODE REVIEW

**Review by jbesraa — CHANGES_REQUESTED** [review]
1) your webpack file can be written in a better way, as discussed yestrday
2) you should not make big pull requests like this one, specially without commeting as asked.
3) I sugeest you add tests, take a look at Enzyme.
4) seprates clients side routes from the entry file (which will have te render function from react-dom and display in the root div at your html file).
4) remove unwanted console logs(db file)
5) is all your devdepend's in use? 
6) take a look here https://babeljs.io/docs/plugins/preset-latest/

**Comment by Karyum** [comment]
hey @esraajb we addressed changes 1, 2, 5, 7.
can you give some guidance on what num 4 should look like?
we will work on testing and sorry about the big pull request.

**Comment by jbesraa** [comment]
see app.jsx and routes.jsx here: https://github.com/esraajb/todos-application/tree/master/src

**Comment by Karyum** [comment]
@esraajb we added the label blocked just because we don't want to add testing and routes on this pull request cause it just gonna make it really massive.
so can you review the other requested changes so we can start opening issues and pull requests for testing and routes in an effort to keep our pull request smaller.

**Review by jbesraa — COMMENTED** [review]
Webpack Do not bundle only .js files.
Change that in your readme and im happy to merge after that
Good job 👍🏼

**Comment by Karyum** [comment]
@esraajb fixed cheers!

**Comment by jbesraa** [comment]
http://blog.andrewray.me/webpack-when-to-use-and-why/

**Comment by jbesraa** [comment]
read the link above. 
ill merge this one but make sure to change the discreption for webpack in a seprate PR. 

you guys should make sure you understand WHY you use new things and WHAT they does, not only how to implemnt them.

**Pull request merged**
